# Generated by Django 4.2.6 on 2023-11-29 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ThienryBooks', '0002_client_login_order_delete_parent_hiring_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('book_title', models.CharField(max_length=50)),
                ('book_author', models.CharField(max_length=50)),
                ('book_needed', models.CharField(max_length=50)),
                ('upload_book', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ThienryBooks.exchange'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
